sudo: required
services: 
  - docker 

before_install:
    - docker build -t mohsen/docker-react -f Dockerfile.dev .

script:
    - docker run mohsen/docker-react npm run test --coverage 

after_success:
  - coveralls

